name: kafka-cluster
services:
  # =====================
  # CONTROLLERS (KRaft)
  # =====================
  kafka-controller-1:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-controller-1
    hostname: kafka-controller-1
    restart: unless-stopped
    networks:
      - lab-network
    ports:
      - "9091:9091"
    environment:
      KAFKA_PROCESS_ROLES: controller
      KAFKA_NODE_ID: 1

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:19092,2@kafka-controller-2:29092,3@kafka-controller-3:39092

      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_LOG_DIRS: /var/lib/kafka/data

      # KAFKA_JMX_PORT: 9101
      # KAFKA_JMX_HOSTNAME: kafka-controller-1
      KAFKA_JMX_OPTS: >
        -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent.jar=9091:/opt/jmx-exporter/kafka-broker.yml
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false

    volumes:
      - kafka-controller-1-data:/var/lib/kafka/data
      - ./jmx-exporter:/opt/jmx-exporter

    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 19092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6

  kafka-controller-2:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-controller-2
    hostname: kafka-controller-2
    ports:
      - "9092:9091"
    restart: unless-stopped
    networks:
      - lab-network
    environment:
      KAFKA_PROCESS_ROLES: controller
      KAFKA_NODE_ID: 2

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:19092,2@kafka-controller-2:29092,3@kafka-controller-3:39092

      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_LOG_DIRS: /var/lib/kafka/data

      # KAFKA_JMX_PORT: 9102
      # KAFKA_JMX_HOSTNAME: kafka-controller-2
      KAFKA_JMX_OPTS: >
        -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent.jar=9091:/opt/jmx-exporter/kafka-broker.yml
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false

    volumes:
      - kafka-controller-2-data:/var/lib/kafka/data
      - ./jmx-exporter:/opt/jmx-exporter

    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 29092 || exit 1"]

  kafka-controller-3:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-controller-3
    hostname: kafka-controller-3
    restart: unless-stopped
    ports:
      - "9093:9091"
    networks:
      - lab-network
    environment:
      KAFKA_PROCESS_ROLES: controller
      KAFKA_NODE_ID: 3

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:19092,2@kafka-controller-2:29092,3@kafka-controller-3:39092

      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_LOG_DIRS: /var/lib/kafka/data

      KAFKA_JMX_PORT: 9103
      KAFKA_JMX_HOSTNAME: kafka-controller-3
      KAFKA_JMX_OPTS: >
        -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent.jar=9091:/opt/jmx-exporter/kafka-broker.yml
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false

    volumes:
      - kafka-controller-3-data:/var/lib/kafka/data
      - ./jmx-exporter:/opt/jmx-exporter

    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 39092 || exit 1"]

  # =====================
  # BROKERS
  # =====================
  kafka-broker-1:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-broker-1
    hostname: kafka-broker-1
    restart: unless-stopped
    ports:
      - "19092:9092"
      - "7071:7071"
    networks:
      - lab-network
    environment:
      KAFKA_PROCESS_ROLES: broker
      KAFKA_NODE_ID: 101

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-1:9093,EXTERNAL://localhost:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:19092,2@kafka-controller-2:29092,3@kafka-controller-3:39092
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_LOG_DIRS: /var/lib/kafka/data

      # KAFKA_JMX_PORT: 9104
      # KAFKA_JMX_HOSTNAME: kafka-broker-1
      KAFKA_JMX_OPTS: >
        -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent.jar=7071:/opt/jmx-exporter/kafka-broker.yml
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false

    volumes:
      - kafka-broker-1-data:/var/lib/kafka/data
      - ./jmx-exporter:/opt/jmx-exporter
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9093 || exit 1"]

  kafka-broker-2:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-broker-2
    hostname: kafka-broker-2
    restart: unless-stopped
    ports:
      - "19093:9092"
      - "7072:7071"
    networks:
      - lab-network
    environment:
      KAFKA_PROCESS_ROLES: broker
      KAFKA_NODE_ID: 102

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-2:9093,EXTERNAL://localhost:19093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:19092,2@kafka-controller-2:29092,3@kafka-controller-3:39092
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_LOG_DIRS: /var/lib/kafka/data

      # KAFKA_JMX_PORT: 9105
      # KAFKA_JMX_HOSTNAME: kafka-broker-2
      KAFKA_JMX_OPTS: >
        -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent.jar=7071:/opt/jmx-exporter/kafka-broker.yml
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false


    volumes:
      - kafka-broker-2-data:/var/lib/kafka/data
      - ./jmx-exporter:/opt/jmx-exporter

  kafka-broker-3:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-broker-3
    hostname: kafka-broker-3
    restart: unless-stopped
    ports:
      - "19094:9092"
      - "7073:7071"
    networks:
      - lab-network
    environment:
      KAFKA_PROCESS_ROLES: broker
      KAFKA_NODE_ID: 103

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-3:9093,EXTERNAL://localhost:19094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:19092,2@kafka-controller-2:29092,3@kafka-controller-3:39092
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_LOG_DIRS: /var/lib/kafka/data

      # KAFKA_JMX_PORT: 9106
      # KAFKA_JMX_HOSTNAME: kafka-broker-3
      KAFKA_JMX_OPTS: >
        -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent.jar=7071:/opt/jmx-exporter/kafka-broker.yml
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false

    volumes:
      - kafka-broker-3-data:/var/lib/kafka/data
      - ./jmx-exporter:/opt/jmx-exporter


  # =====================
  # Misc
  # =====================

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.6.0
    container_name: kafka-connect
    restart: unless-stopped
    ports:
      - "8083:8083"
    networks:
      - lab-network
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka-broker-1:9093,kafka-broker-2:9093,kafka-broker-3:9093
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: connect-cluster
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
    depends_on:
      - kafka-broker-1


volumes:
  kafka-controller-1-data:
  kafka-controller-2-data:
  kafka-controller-3-data:
  kafka-broker-1-data:
  kafka-broker-2-data:
  kafka-broker-3-data:

networks:
  lab-network:
    external: true