services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    networks:
      - lab-network
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local-kraft-CLUSTER_ID
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker-1:9093,kafka-broker-2:9093,kafka-broker-3:9093
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.0
    container_name: schema-registry
    networks:
      - lab-network
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-broker-1:9093,kafka-broker-2:9093,kafka-broker-3:9093
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

networks:
  lab-network:
    external: true